#+TITLE: DPS-Kissat
#+AUTHOR:  Hidetomo Nabeshima, Tsubasa Fukiage, Yuto Obitsu, Xiao-Nan LU, and Katsumi Inoue

DPS is a new framework for easily constructing efficient deterministic
parallel SAT solvers, providing the delayed clause exchange technique
introduced in [[https://github.com/nabesima/manyglucose-satcomp2020][ManyGlucose]]. DPS-Kissat applies our framework to [[http://fmv.jku.at/kissat/][Kissat]],
a state-of-the-art sequential SAT solver.

* How to build a docker container for AWS environment

: % cd leader
: % docker build -t dps:leader .

~dps:leader~ container is based on ~satcomp-base:leader~ container
provided by
https://github.com/aws-samples/aws-batch-comp-infrastructure-sample.
DPS-Kissat is a parallel SAT solver for shared memory
environments. Thus we do not require a worker container.
# Given a problem, the container starts 32 threads that each run
# Kissat and solve the problem as a portfolio solver.  DPS-Kissat
# adopts the following simple diversity strategy 1. random variable
# selection up to the first contradiction 2. disabled elimination in
# half of the workers.
